/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.indicator.kafka;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TestAvroRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 150623045565153282L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TestAvroRecord\",\"namespace\":\"io.indicator.kafka\",\"fields\":[{\"name\":\"guid\",\"type\":\"string\"},{\"name\":\"eventTimestamp\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TestAvroRecord> ENCODER =
      new BinaryMessageEncoder<TestAvroRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TestAvroRecord> DECODER =
      new BinaryMessageDecoder<TestAvroRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TestAvroRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TestAvroRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TestAvroRecord>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TestAvroRecord to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TestAvroRecord from a ByteBuffer. */
  public static TestAvroRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public CharSequence guid;
  @Deprecated public long eventTimestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TestAvroRecord() {}

  /**
   * All-args constructor.
   * @param guid The new value for guid
   * @param eventTimestamp The new value for eventTimestamp
   */
  public TestAvroRecord(CharSequence guid, Long eventTimestamp) {
    this.guid = guid;
    this.eventTimestamp = eventTimestamp;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return guid;
    case 1: return eventTimestamp;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: guid = (CharSequence)value$; break;
    case 1: eventTimestamp = (Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'guid' field.
   * @return The value of the 'guid' field.
   */
  public CharSequence getGuid() {
    return guid;
  }

  /**
   * Sets the value of the 'guid' field.
   * @param value the value to set.
   */
  public void setGuid(CharSequence value) {
    this.guid = value;
  }

  /**
   * Gets the value of the 'eventTimestamp' field.
   * @return The value of the 'eventTimestamp' field.
   */
  public Long getEventTimestamp() {
    return eventTimestamp;
  }

  /**
   * Sets the value of the 'eventTimestamp' field.
   * @param value the value to set.
   */
  public void setEventTimestamp(Long value) {
    this.eventTimestamp = value;
  }

  /**
   * Creates a new TestAvroRecord RecordBuilder.
   * @return A new TestAvroRecord RecordBuilder
   */
  public static io.indicator.kafka.TestAvroRecord.Builder newBuilder() {
    return new io.indicator.kafka.TestAvroRecord.Builder();
  }

  /**
   * Creates a new TestAvroRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TestAvroRecord RecordBuilder
   */
  public static io.indicator.kafka.TestAvroRecord.Builder newBuilder(io.indicator.kafka.TestAvroRecord.Builder other) {
    return new io.indicator.kafka.TestAvroRecord.Builder(other);
  }

  /**
   * Creates a new TestAvroRecord RecordBuilder by copying an existing TestAvroRecord instance.
   * @param other The existing instance to copy.
   * @return A new TestAvroRecord RecordBuilder
   */
  public static io.indicator.kafka.TestAvroRecord.Builder newBuilder(io.indicator.kafka.TestAvroRecord other) {
    return new io.indicator.kafka.TestAvroRecord.Builder(other);
  }

  /**
   * RecordBuilder for TestAvroRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TestAvroRecord>
    implements org.apache.avro.data.RecordBuilder<TestAvroRecord> {

    private CharSequence guid;
    private long eventTimestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.indicator.kafka.TestAvroRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.guid)) {
        this.guid = data().deepCopy(fields()[0].schema(), other.guid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventTimestamp)) {
        this.eventTimestamp = data().deepCopy(fields()[1].schema(), other.eventTimestamp);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TestAvroRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(io.indicator.kafka.TestAvroRecord other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.guid)) {
        this.guid = data().deepCopy(fields()[0].schema(), other.guid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventTimestamp)) {
        this.eventTimestamp = data().deepCopy(fields()[1].schema(), other.eventTimestamp);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'guid' field.
      * @return The value.
      */
    public CharSequence getGuid() {
      return guid;
    }

    /**
      * Sets the value of the 'guid' field.
      * @param value The value of 'guid'.
      * @return This builder.
      */
    public io.indicator.kafka.TestAvroRecord.Builder setGuid(CharSequence value) {
      validate(fields()[0], value);
      this.guid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'guid' field has been set.
      * @return True if the 'guid' field has been set, false otherwise.
      */
    public boolean hasGuid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'guid' field.
      * @return This builder.
      */
    public io.indicator.kafka.TestAvroRecord.Builder clearGuid() {
      guid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventTimestamp' field.
      * @return The value.
      */
    public Long getEventTimestamp() {
      return eventTimestamp;
    }

    /**
      * Sets the value of the 'eventTimestamp' field.
      * @param value The value of 'eventTimestamp'.
      * @return This builder.
      */
    public io.indicator.kafka.TestAvroRecord.Builder setEventTimestamp(long value) {
      validate(fields()[1], value);
      this.eventTimestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'eventTimestamp' field has been set.
      * @return True if the 'eventTimestamp' field has been set, false otherwise.
      */
    public boolean hasEventTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'eventTimestamp' field.
      * @return This builder.
      */
    public io.indicator.kafka.TestAvroRecord.Builder clearEventTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TestAvroRecord build() {
      try {
        TestAvroRecord record = new TestAvroRecord();
        record.guid = fieldSetFlags()[0] ? this.guid : (CharSequence) defaultValue(fields()[0]);
        record.eventTimestamp = fieldSetFlags()[1] ? this.eventTimestamp : (Long) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TestAvroRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<TestAvroRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TestAvroRecord>
    READER$ = (org.apache.avro.io.DatumReader<TestAvroRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
